---
- hosts: load_generators
  any_errors_fatal: true
  tasks:

  - name: SGLOAD | Delete previous sgload if there is one
    file:
      path: /opt/go/src/github.com/couchbaselabs
      state: absent
    become: yes

  - name: SGLOAD | go get sgload
    shell: GOPATH=/opt/go go get -u -v github.com/couchbaselabs/sgload
    become: yes

  - name: SGLOAD | Symlink sgload into /usr/local/bin
    file: src=/opt/go/bin/sgload dest=/usr/local/bin/sgload owner=centos group=centos state=link
    become: yes

  - name: SGLOAD | Sysctl file to increase available port range for outgoing socket connections
    copy: src=files/sysctld_increase_port_range.conf dest=/etc/sysctl.d/20-increase-port-range.conf owner=root group=root mode=0644
    become: yes

  - name: SGLOAD | Shell cmd to increase available port range for outgoing socket connections
    shell: sysctl --system
    become: yes



