---
- hosts: couchbase_servers
  any_errors_fatal: true
  become: yes

  vars:
    couchbase_server_package_base_url:
    couchbase_server_package_name:
    ipv6_enabled:
    couchbase_server_package_url: "{{ couchbase_server_package_base_url }}/{{ couchbase_server_package_name }}"


    couchbase_server_admin: Administrator
    couchbase_server_password: password

    # 512 reserved for query service
    couchbase_server_index_ram: 512
    couchbase_server_cluster_ram: "{{((ansible_memtotal_mb|int)*0.8)|int - 512 }}"
    couchbase_server_admin_port: "{{ couchbase_server_admin_port }}"
    protocol: http://
    addnode_protocol: http://
    addnode_port: 18091
    ssl_verify:
    couchbase_server_home_path: /opt/couchbase

    # Primary node
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"

    # Current node
    couchbase_server_node: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

    couchbase_server_bucket_type: couchbase
    couchbase_server_bucket_replica: 1
    couchbase_server_bucket_ram: "{{ ((couchbase_server_cluster_ram|int)*0.5)|int }}"

  tasks:
    - debug: msg="Couchbase server primary node {{ couchbase_server_primary_node }}"
    - debug: msg="Couchbase server node {{ couchbase_server_node }}"
    - debug: msg="Downloading Couchbase server v. {{ couchbase_server_package_url }}"
    - debug: msg="IPv6 Enabled - {{ ipv6_enabled }}"

    # Configure
    - debug: msg="Couchbase cluster RAM {{ couchbase_server_cluster_ram }}"
    - debug: msg="Couchbase bucket RAM {{ couchbase_server_bucket_ram }}"

    - name: COUCHBASE SERVER | Get major version
      shell: cat /opt/couchbase/VERSION.txt | cut -d '.' -f1
      register: cb_major_version

    - name: COUCHBASE SERVER | Get full version
      shell: cat /opt/couchbase/VERSION.txt
      register: cb_full_version

    - name: COUCHBASE SERVER | Wait for node to be listening on port 8091
      wait_for: port="{{ couchbase_server_admin_port }}" delay=5 timeout=60

    - name: COUCHBASE SERVER | Configure cluster settings (3.0.X and 3.1.X)
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli cluster-init -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-port={{couchbase_server_admin_port}} --cluster-ramsize={{ couchbase_server_cluster_ram }}"
      when:  "'3.0' in couchbase_server_package_name or '3.1' in couchbase_server_package_name"

    - name: COUCHBASE SERVER | Configure cluster settings (4.0.X and 4.1.X)
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli cluster-init -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-port={{couchbase_server_admin_port}} --cluster-ramsize={{ couchbase_server_cluster_ram }}  --services=data,index,query  --cluster-index-ramsize={{ couchbase_server_index_ram }}"
      when:  "'4.0' in couchbase_server_package_name or '4.1' in couchbase_server_package_name"

    - name: COUCHBASE SERVER | Configure cluster settings (4.5.X and 4.6.X)
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli cluster-init -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-port={{couchbase_server_admin_port}} --cluster-ramsize={{ couchbase_server_cluster_ram }}  --services=data,index,query  --cluster-index-ramsize={{ couchbase_server_index_ram }}  --index-storage-setting=default"
      when:  "'4.5' in couchbase_server_package_name or '4.6' in couchbase_server_package_name"

    - name: COUCHBASE SERVER | Configure cluster settings (4.7.X and up) | configure IPv4
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli cluster-init -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --cluster-username={{ couchbase_server_admin }} --cluster-password={{ couchbase_server_password }} --cluster-port={{couchbase_server_admin_port}} --cluster-ramsize={{ couchbase_server_cluster_ram }}  --services=data,index,query  --cluster-index-ramsize={{ couchbase_server_index_ram }}  --index-storage-setting=default"
      when:  "not '4.0' in couchbase_server_package_name and not '4.1' in couchbase_server_package_name and not '4.5' in couchbase_server_package_name and not '4.6' in couchbase_server_package_name and not '3.0' in couchbase_server_package_name and not '3.1' in couchbase_server_package_name and not ipv6_enabled"

    - name: COUCHBASE SERVER | Configure cluster settings (4.7.X and up) | configure IPv6
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli cluster-init -c [{{ couchbase_server_node }}]:{{ couchbase_server_admin_port }} --cluster-username={{ couchbase_server_admin }} --cluster-password={{ couchbase_server_password }} --cluster-port={{couchbase_server_admin_port}} --cluster-ramsize={{ couchbase_server_cluster_ram }}  --services=data,index,query  --cluster-index-ramsize={{ couchbase_server_index_ram }}  --index-storage-setting=default"
      when:  "not '4.0' in couchbase_server_package_name and not '4.1' in couchbase_server_package_name and not '4.5' in couchbase_server_package_name and not '4.6' in couchbase_server_package_name and not '3.0' in couchbase_server_package_name and not '3.1' in couchbase_server_package_name and ipv6_enabled"

    - name: COUCHBASE SERVER | Initialize primary node (3.x only)
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli node-init -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --node-init-hostname={{ couchbase_server_node }}"
      when: "'3.0' in couchbase_server_package_name or '3.1' in couchbase_server_package_name"

    - name: COUCHBASE SERVER | Initialize primary node (4.X and 5.X) | configure IPv4
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli node-init -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --node-init-hostname={{ couchbase_server_node }}"
      when: "{{ cb_major_version['stdout'] | search('\\b[4-5]\\b') }} and not ipv6_enabled"

    - name: COUCHBASE SERVER | Initialize primary node (4.X and 5.X) | configure IPv6
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli node-init -c [{{ couchbase_server_node }}]:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --node-init-hostname={{ couchbase_server_node }}"
      when: "{{ cb_major_version['stdout'] | search('\\b[4-5]\\b') }} and ipv6_enabled"

    - name: COUCHBASE SERVER | Initialize primary node (6.X and up) | configure IPv4
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli node-init -c {{ couchbase_server_node }}:{{ couchbase_server_admin_port }} -u={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --node-init-hostname={{ couchbase_server_node }}"
      when: "(not {{ cb_major_version['stdout'] | search('\\b[1-5]\\b') }}) and not ipv6_enabled"

    - name: COUCHBASE SERVER | Initialize primary node (6.X and up)| configure IPv6
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli node-init -c [{{ couchbase_server_node }}]:{{ couchbase_server_admin_port }} -u={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --node-init-hostname={{ couchbase_server_node }}"
      when: "(not {{ cb_major_version['stdout'] | search('\\b[1-5]\\b') }}) and ipv6_enabled"

    - name: COUCHBASE SERVER | Wait for node to be listening on port 8091
      wait_for: port="{{ couchbase_server_admin_port }}" delay=5 timeout=60
  
    - set_fact:
        protocol: ""
        addnode_protocol: ""
      when: "( {{ cb_major_version['stdout'] | search('\\b[1-4]\\b') }} ) or ( '5.0.0' in cb_full_version.stdout )"

    - set_fact:
        addnode_protocol: https://
        addnode_port: 18091
        ssl_verify: --no-ssl-verify
      when: "( {{ cb_major_version['stdout'] | search('\\b[7]\\b') }} ) or ( '7.1.0' in cb_full_version.stdout )"

    - name: COUCHBASE SERVER | Join additional cluster nodes | configure IPv4
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add -c {{ addnode_protocol }}{{ couchbase_server_primary_node }}:{{ addnode_port }} -u={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add={{ addnode_protocol }}{{ couchbase_server_node }}:{{ addnode_port }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }} {{ ssl_verify }}"
      when: "not (couchbase_server_node == couchbase_server_primary_node ) and not ipv6_enabled"

    - name: COUCHBASE SERVER | Join additional cluster nodes | configure IPv6
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add -c {{ addnode_protocol }}[{{ couchbase_server_primary_node }}]:{{ addnode_port }} -u={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add={{ addnode_protocol }}{{ couchbase_server_node }}:{{ addnode_port }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }} {{ ssl_verify }}"
      when: "not (couchbase_server_node == couchbase_server_primary_node ) and ipv6_enabled"

    - name: COUCHBASE SERVER | Rebalance cluster (6.X and up) | configure IPv4
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} -u={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
      ignore_errors: yes
      when: "(not {{ cb_major_version['stdout'] | search('\\b[1-5]\\b') }}) and not ipv6_enabled"

    - name: COUCHBASE SERVER | Rebalance cluster (6.X and up) | configure IPv6
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance -c [{{ couchbase_server_primary_node }}]:{{ couchbase_server_admin_port }} -u={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
      ignore_errors: yes
      when: "(not {{ cb_major_version['stdout'] | search('\\b[1-5]\\b') }}) and ipv6_enabled"

    - name: COUCHBASE SERVER | Rebalance cluster (3.X to 5.X) | configure IPv4
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
      ignore_errors: yes
      when: "{{ cb_major_version['stdout'] | search('\\b[3-5]\\b')}} and not ipv6_enabled"

    - name: COUCHBASE SERVER | Rebalance cluster (3.X to 5.X) | configure IPv6
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance -c [{{ couchbase_server_primary_node }}]:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
      ignore_errors: yes
      when: "{{ cb_major_version['stdout'] | search('\\b[3-5]\\b')}} and ipv6_enabled"

    - name: COUCHBASE SERVER | Enable auto failover (6.X and up) | configure IPv4
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli setting-autofailover -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} -u={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --enable-auto-failover=1 --auto-failover-timeout=30"
      when:  "(not {{ cb_major_version['stdout'] | search('\\b[1-5]\\b') }}) and not ipv6_enabled"

    - name: COUCHBASE SERVER | Enable auto failover (6.X and up) | configure IPv6
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli setting-autofailover -c [{{ couchbase_server_primary_node }}]:{{ couchbase_server_admin_port }} -u={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --enable-auto-failover=1 --auto-failover-timeout=30"
      when:  "(not {{ cb_major_version['stdout'] | search('\\b[1-5]\\b') }}) and ipv6_enabled"

    - name: COUCHBASE SERVER | Enable auto failover (3.X to 5.X) | configure IPv4
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli setting-autofailover -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --enable-auto-failover=1 --auto-failover-timeout=30"
      when: "{{ cb_major_version['stdout'] | search('\\b[3-5]\\b')}} and not ipv6_enabled"

    - name: COUCHBASE SERVER | Enable auto failover (3.X to 5.X) | configure IPv6
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli setting-autofailover -c [{{ couchbase_server_primary_node }}]:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --enable-auto-failover=1 --auto-failover-timeout=30"
      when: "{{ cb_major_version['stdout'] | search('\\b[3-5]\\b')}} and ipv6_enabled"
