- name: Windows - Copy directory to Windows
  hosts: windows
  vars:
    directory_path:

  tasks:
    - name: Remove LiteServ on machine (if exists)
      win_file: path=C:\Users\Administrator\Desktop\LiteServ state=absent

    - name: Copy Directory
      win_copy: src={{ directory_path }}  dest=C:\Users\Administrator\Desktop\LiteServ\