---
# Deploy sync gateway configs
- hosts: sync_gateways

  vars:
    sync_gateway_config_filepath:
    sslcert:
    sslkey:
    x509_auth:
    x509_certs_dir:
    cacertpath:

  tasks:
  - include: tasks/deploy-sync-gateway-config.yml
    sudo: yes
    sudo: root
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - include: tasks/deploy-sync-gateway-config-macos.yml
    when: ansible_os_family == "Darwin"

  - include: tasks/deploy-sync-gateway-config-windows.yml
    when: ansible_os_family == "Windows"
