- name: Windows - Download Testserver Java WebService Package
  hosts: windows
  vars:
    testserver_download_url:
    cblite_download_url:
    war_package_name:
    core_package_name:
    build_name:

  tasks:
  - debug:
      msg: "testserver_download_url: {{ testserver_download_url }}"

  - debug:
      msg: "cblite_download_url: {{ cblite_download_url }}"

  - debug:
      msg: "war_package_name {{ war_package_name }}.war"

  - debug:
      msg: "core_package_name {{ core_package_name }}.zip"

  - debug:
      msg: "build_name {{ build_name }}"

  - win_stat:
      path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\{{ war_package_name }}.war
    register: war_st

  - win_stat:
      path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\{{ core_package_name }}.zip
    register: core_st

  - name: Delete any exiting pre-downloaded files
    win_file:
      path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\*
      state: absent
    when: war_st.stat.exists == False and core_st.stat.exists == False
    ignore_errors: yes

  - debug:
      msg: "{{ build_name }} already present, skipping download..."
    when: war_st.stat.exists == False and core_st.stat.exists == False

  - name: Create TestServer directory
    win_file:
      path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}
      state: directory
    when: war_st.stat.exists == False and core_st.stat.exists == False

  - name: Download TestServer Java WebService .war
    win_get_url:
      url: "{{ testserver_download_url }}"
      dest: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\{{ war_package_name }}.war
      skip_certificate_validation: yes
      validate_certs: no
    when: war_st.stat.exists == False

  - name: Download Couchbase Lite Library .zip
    win_get_url:
      url: "{{ cblite_download_url }}"
      dest: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\{{ core_package_name }}.zip
      skip_certificate_validation: yes
      validate_certs: no
    when: core_st.stat.exists == False

  - name: Unzip Couchbase Lite Library and remove .zip
    win_unzip:
      src: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\{{ core_package_name }}.zip
      dest: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}
      rm: true
