- name: Windows - Download Testserver Java Desktop Package
  hosts: windows
  vars:
    download_url:
    package_name:
    build_name:

  tasks:
  - debug:
      msg: "download_url: {{ download_url }}"

  - debug:
      msg: "package_name {{ package_name }}.zip"

  - debug:
      msg: "build_name {{ build_name }}"

  - win_stat:
      path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\{{package_name}}.zip
    register: pkg_st

  - win_stat:
      path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\TestServerJava.exe
    register: prunsrv_st

  - name: Remove TestServerJava service
    win_command: chdir=C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }} C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\win_service_manager.bat TestServerJava remove
    when: prunsrv_st.stat.exists == True
    ignore_errors: yes

  - name: Delete any exiting pre-downloaded files
    win_file:
      path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\*
      state: absent
    when: pkg_st.stat.exists == False
    ignore_errors: yes

  - debug:
      msg: "{{ build_name }} already present, skipping download..."
    when: pkg_st.stat.exists == True

  - name: Create TestServer directory
    win_file:
      path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}
      state: directory
    when: pkg_st.stat.exists == False

  - name: Download TestServer Java .zip
    win_get_url:
      url: "{{ download_url }}"
      dest: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\{{ package_name }}.zip
      skip_certificate_validation: yes
      validate_certs: no
    when: pkg_st.stat.exists == False

  - name: Unzip TestServer package and remove .zip
    win_unzip:
      src: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\{{ package_name }}.zip
      dest: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}
      rm: true
