- name: Download Testserver Java Desktop
  hosts: testserver
  vars:
    download_url:
    cblite_download_url:
    core_package_name:
    package_name:

  tasks:
  - debug:
      msg: "download_url: {{ download_url }}"

  - debug:
      msg: "cblite_download_url: {{ cblite_download_url }}"

  - debug:
      msg: "package_name {{ package_name }}.zip"

  - name: Delete any exiting pre-downloaded files
    file:
      path: ~/javatestserver
      state: absent

  - name: Set javatestserver location
    stat:
      path: ~/javatestserver

  - name: create javatestserver directory if not exists
    file:
      path: ~/javatestserver
      state: directory

  - name: Download TestServer Java .zip
    get_url:
      url: "{{ download_url }}"
      dest: ~/javatestserver/{{ package_name }}.zip

  - name: Unzip TestServer Java Package and remove .zip
    unarchive: src=~/javatestserver/{{ package_name }}.zip dest=~/javatestserver copy=no

  - name: Download Couchbase Lite Library .zip
    get_url:
      url: "{{ cblite_download_url }}"
      dest: ~/javatestserver/{{ core_package_name }}.zip

  - name: Unzip Couchbase Lite Library and remove .zip
    unarchive: src=~/javatestserver/{{ core_package_name }}.zip dest=~/javatestserver copy=no
