- name: Windows - Download LiteServ
  hosts: windows
  tasks:

    - name: Install nssm (https://nssm.cc/)
      win_chocolatey: name=nssm

    - name: Remove Service Wrapper
      win_nssm:
        name: LiteServ
        start_mode: manual
        application: C:\Users\Administrator\Desktop\LiteServ\LiteServ\LiteServ.exe
        status: absent

    - name: Delete Existing LiteServ
      win_file: path=C:\\Users\\Administrator\\Desktop\\LiteServ state=absent

    - name: Create LiteServ Directory
      win_file: path=C:\\Users\\Administrator\\Desktop\\LiteServ state=directory

    - name: Download LiteServ to Desktop for Administrator
      win_get_url:
        url: "http://latestbuilds.hq.couchbase.com/couchbase-lite-net/1.4.0/43/LiteServ.zip"
        dest: "C:\\Users\\Administrator\\Desktop\\LiteServ\\LiteServ.zip"

    - name: Extract LiteServ.zip -> LiteServ
      win_unzip:
        src: "C:\\Users\\Administrator\\Desktop\\LiteServ\\LiteServ.zip"
        dest: "C:\\Users\\Administrator\\Desktop\\LiteServ\\LiteServ"

    - name: Remove LiteServ.zip
      win_file: path=C:\\Users\\Administrator\\Desktop\\LiteServ\\LiteServ.zip state=absent

    - name: Install nssm service wrapper
      win_nssm:
        name: LiteServ
        status: present
        start_mode: manual
        application: C:\Users\Administrator\Desktop\LiteServ\LiteServ\LiteServ.exe
