- name: Windows - Download LiteServ Package
  hosts: windows
  vars:
    download_url:
    package_name:

  tasks:
  - debug:
      msg: "download_url {{ download_url }}, package_name {{ package_name }}"

  - win_stat:
      path: C:\Users\{{ ansible_user }}\Desktop\LiteServ\{{ package_name }}\net45\LiteServ.exe
    register: st

  - name: Delete any exiting packages
    win_file: 
      path: C:\Users\{{ ansible_user }}\Desktop\LiteServ 
      state: absent
    when: st.stat.exists == False

  - debug:
      msg: "{{ package_name }} already present, skipping download..."
    when: st.stat.exists

  - name: Create LiteServ directory
    win_file: 
      path: C:\Users\{{ ansible_user }}\Desktop\LiteServ\{{ package_name }}
      state: directory
    when: st.stat.exists == False

  - name: Download LiteServ Windows .zip
    win_get_url:
      url: "{{ download_url }}"
      dest: C:\Users\{{ ansible_user }}\Desktop\LiteServ\{{ package_name }}.zip
    when: st.stat.exists == False

  - name: Unzip package and remove .zip
    win_unzip:
      src: C:\Users\{{ ansible_user }}\Desktop\LiteServ\{{ package_name }}.zip
      dest: C:\Users\{{ ansible_user }}\Desktop\LiteServ\{{ package_name }}
      rm: true
    when: st.stat.exists == False
