---
# Remove sync_gateway
- hosts: sync_gateways
  become_user: root

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sync_gateway_package:
    couchbase_sync_gateway_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}"
    x509_auth:

  tasks:
  - include: tasks/remove-sync-gateway.yml
  - include: tasks/clean-users.yml

  # Check no sync_gateways or accels running
  - name: SYNC GATEWAY | verify no service on 4985
    wait_for: port=4985 delay=1 state=stopped

# Flush server buckets
- hosts: couchbase_servers
  any_errors_fatal: true
  become: yes
  vars:
    # Primary node
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    # Current node
    couchbase_server_node: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

    couchbase_server_home_path: /opt/couchbase
    couchbase_server_admin_port: 8091
    couchbase_server_admin: Administrator
    couchbase_server_password: password

    couchbase_server_bucket_type: couchbase
    couchbase_server_bucket_replica: 1
    couchbase_server_cluster_ram: "{{ ((ansible_memtotal_mb|int)*0.8)|int - 512 }}"
    couchbase_server_bucket_ram: "{{ ((couchbase_server_cluster_ram|int)*0.5)|int }}"

# Create sync_gateway user
- hosts: sync_gateways
  any_errors_fatal: true
  become_user: root
  tasks:
  - include: tasks/create-sync-gateway-user.yml
  ignore_errors: yes

# Download sync_gateway package
- hosts: sync_gateways
  any_errors_fatal: true
  become_user: root

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sync_gateway_package:
    couchbase_sync_gateway_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}"
    couchbase_server_primary_node:

  tasks:
  - name: SYNC GATEWAY |  Download sync_gateway tar gz {{ couchbase_sync_gateway_package_url }}
    get_url: url={{ couchbase_sync_gateway_package_url }} dest=/tmp/{{ couchbase_sync_gateway_package }} validate_certs=False

# Install sync_gateway
- hosts: sync_gateways
  any_errors_fatal: true
  become: yes

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sg_accel_package:
    couchbase_sg_accel_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sg_accel_package }}"
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
  tasks:
  - include: tasks/install-sg.yml

# Copy certs to /Users/sync_gateway dir
  - name: Copying certs.zip to /Users/sync_gateway directory
    shell: cp /tmp/certs.zip /Users/sync_gateway
    when: x509_auth

# Deleting cert directory if exist
  - name: Deleting /Users/sync_gateway/certs
    shell: rm -rf /Users/sync_gateway/certs/*
    when: x509_auth

# unzip certs.zip
  - name: Unzipping certs.zip
    shell: unzip /Users/sync_gateway/certs.zip -d /Users/sync_gateway/certs
    when: x509_auth

# Deploy non writer sync_gateway configs
- hosts: sync_gateways
  any_errors_fatal: true
  become: yes
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    sync_gateway_node: "{{ hostvars[groups.sync_gateways[0]].ansible_host }}"
    is_index_writer: "false"
    sslcert:
    sslkey:
    cacertpath:
    certpath:
    keypath:
    username:
    password:

  tasks:
  - include: tasks/deploy-sync-gateway-config-macos.yml

# Launch sync_gateway service
- hosts: sync_gateways
  any_errors_fatal: true
  become: yes
  tasks:
  - include: tasks/start-sync-gateway-macos.yml
