---
- hosts: couchbase_servers
  any_errors_fatal: true
  become: yes

  vars:
   
    # Primary node
    gilad: "zhovna"

  tasks:
    - debug: msg="Couchbase server primary node {{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
   