---
# Remove sync_gateway
- hosts: sync_gateways

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sync_gateway_package:
    couchbase_sync_gateway_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}"

  tasks:
  - include: tasks/stop-sync-gateway-windows.yml
  - include: tasks/remove-sync-gateway-windows.yml

# Flush server buckets
- hosts: couchbase_servers
  any_errors_fatal: true
  vars:
    # Primary node
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"

    # Current node
    couchbase_server_node: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

    couchbase_server_home_path: /opt/couchbase
    couchbase_server_admin_port: 8091
    couchbase_server_admin: Administrator
    couchbase_server_password: password

    couchbase_server_bucket_type: couchbase
    couchbase_server_bucket_replica: 1
    couchbase_server_cluster_ram: "{{ ((ansible_memtotal_mb|int)*0.8)|int - 512 }}"
    couchbase_server_bucket_ram: "{{ ((couchbase_server_cluster_ram|int)*0.5)|int }}"

# Download sync_gateway package
- hosts: sync_gateways
  any_errors_fatal: true

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sync_gateway_package:
    couchbase_sync_gateway_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}"
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"

  tasks:
  - name: SYNC GATEWAY |  Download sync_gateway exe {{ couchbase_sync_gateway_package_url }}
    win_get_url: url={{ couchbase_sync_gateway_package_url }} dest="C:\Users\Administrator\AppData\Local\Temp\{{ couchbase_sync_gateway_package }}"
  
# Install sync_gateway
- hosts: sync_gateways
  any_errors_fatal: true
  tasks:
  - include: tasks/install-sg-windows.yml

# Deploy non writer sync_gateway configs
- hosts: sync_gateways
  any_errors_fatal: true
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    # hack until mobile-testkit/issues/406 allows any sync gateway to be referenced
    sync_gateway_node: "{{ hostvars[groups.sync_gateways[0]].ansible_host }}"
    is_index_writer: "false"
  tasks:
  - include: tasks/deploy-sync-gateway-config-windows.yml
 
# Launch sync_gateway service
- hosts: sync_gateways
  any_errors_fatal: true
  tasks:
  - include: tasks/start-sync-gateway-windows.yml
