---
- hosts: pool
  any_errors_fatal: true
  become: yes

  vars:
    aws_access_key_id:
    aws_secret_access_key:

  tasks:
  - name: AWS CREDS | Create .aws directory if it doesn't already exist
    file: path=/root/.aws state=directory
  - name: AWS CREDS | Upload templated aws credentials file
    template: src=files/aws_credentials_template dest=/root/.aws/credentials

