- name: Manage TestServer Java Desktop as Daemon Service
  hosts: testserver
  vars:
    service_status:
    package_name:
    java_home:
    jsvc_home:

  tasks:
  - debug: msg="JAVA_HOME location is {{ java_home }}"
  - debug: msg="JSVC_HOME location is {{ jsvc_home }}"

  - name: Stop TestServer Java Daemon Service
    shell: "~/javatestserver/daemon_manager.sh stop ~/javatestserver/{{ package_name }}.jar ~/javatestserver/output {{ java_home }} {{ jsvc_home }}"
    when: "{{ service_status | search('stop') }}"
    ignore_errors: yes
