- name: Manage Tomcat which contains Testserver Java WebService
  hosts: testserver
  vars:
    service_status:
    catalina_base:

  tasks:
  - name: Stop Tomcat Service
    command: "{{ catalina_base }}/bin/catalina.sh stop 30 -force"
    ignore_errors: yes
  
  - debug: msg="{{ catalina_base }}/bin/catalina.sh {{service_status}}"
  - name: Start Tomcat Service
    command: nohup export LD_LIBRARY_PATH=~/javatestserver && {{ catalina_base }}/bin/catalina.sh start
    when: "{{ service_status | search('start') }}"
