---
- hosts: cb1
  any_errors_fatal: true
  tasks:

  tasks:
  - name: CBCOLLECT INFO | Run collectcb_info
    shell: curl 'http://Administrator:password@localhost:8091/controller/startLogsCollection' --data 'uploadHost=s3.amazonaws.com%2Fcb-customers&customer=mobileperf&nodes=*'
    register: curl_out

  - name: CBCOLLECT INFO | Dump curl stdout/stderr
    debug: msg="{{ curl_out.stdout }} {{ curl_out.stderr }}"



