- hosts: couchbase_servers
  any_errors_fatal: true
  become: yes

  tasks:
  # Remove Couchbase Server
  - include: tasks/remove-couchbase-server.yml

  # Remove nginx
  - include: tasks/remove-nginx.yml

  # Check no servers are running
  - name: ALL | verify no servers not listening on port 8081
    wait_for: port=8091 delay=1 state=stopped