# Reset the hosts to the state which test requires
- hosts: sync_gateways

  tasks:
  - name: OS | Reset the clocks
    become: yes
    shell: |
      timedatectl set-ntp true
      date
    ignore_errors: True
    register: ps
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" or ansible_os_family == "Darwin"

  - debug: 
      msg: "printing reset clocks std out {{ ps.stdout }}"
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" or ansible_os_family == "Darwin"
