# Reset the hosts to the state which test requires
- hosts: couchbase_servers

  tasks:
  - name: OS | Reset the clocks
    become: yes
    command: timedatectl set-ntp false | timedatectl set-ntp true
    ignore_errors: True
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" or ansible_os_family == "Darwin"


- hosts: sync_gateways

  tasks:
  - name: OS | Reset the clocks
    become: yes
    command: timedatectl set-ntp false | timedatectl set-ntp true
    ignore_errors: True
    when: ansible_os_family == "Darwin"
