---
- hosts: sync_gateways
  
  tasks:
  - include: tasks/stop-sync-gateway.yml
    become: yes
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu"

  - include: tasks/stop-sync-gateway-windows.yml
    when: ansible_os_family == "Windows"

- hosts: sync_gateways
  any_errors_fatal: true
  
  tasks:
  - include: tasks/start-sync-gateway.yml
    become: yes
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu"

  - include: tasks/start-sync-gateway-windows.yml
    when: ansible_os_family == "Windows"

- hosts: sg_accels
  
  tasks:
  - include: tasks/stop-sg-accel.yml
    become: yes
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu"

  - include: tasks/stop-sg-accel-windows.yml
    when: ansible_os_family == "Windows"

- hosts: sg_accels
  any_errors_fatal: true
  
  tasks:
  - include: tasks/start-sg-accel.yml
    become: yes
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu"

  - include: tasks/start-sg-accel-windows.yml
    when: ansible_os_family == "Windows"