---
# Deploy sync gateway configs
- hosts: sync_gateways
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    # hack until mobile-testkit/issues/406 allows any sync gateway to be referenced
    sync_gateway_node: "{{ hostvars[groups.sync_gateways[0]].ansible_host }}"
    webhook_ip: "{{ hostvars[groups.webhook_ip[0]].ansible_host }}"
    is_index_writer: "false"
  tasks:
  - include: tasks/deploy-sync-gateway-config.yml

- hosts: sync_gateways
  any_errors_fatal: true
  become: yes

  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
  tasks:
  - include: tasks/start-sync-gateway.yml
