---
- hosts: sg_accels
  any_errors_fatal: true

  tasks:
  - include: tasks/stop-sg-accel.yml
    when: ansible_distribution == "CentOS"

  - include: tasks/stop-sg-accel-windows.yml
    when: ansible_os_family == "Windows"