---
- hosts: sg_accels
  any_errors_fatal: true

  tasks:
  - include: tasks/stop-sg-accel.yml
    become: yes
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - include: tasks/stop-sg-accel-windows.yml
    when: ansible_os_family == "Windows"