# Delete the provided directory
- name: SYNC GATEWAY | Create sync_gateway empty file {{ file_name }} of size {{ file_size }}
  become: yes
  shell: dd if=/dev/zero of={{ file_name }} bs={{ file_size }} count=1

- name: SYNC GATEWAY | Change the mode permissions
  become: yes
  shell: chmod 777 {{ file_name }}


- name: SYNC GATEWAY | Change the user/group permissions
  become: yes
  shell: chown {{ owner }}:{{ group }} {{ file_name }}
