# Delete logs and .pindex files
- name: SYNC GATEWAY | Delete sync_gateway logs on Windows
  become: no
  win_file:
    path: "C:/PROGRA~2/Couchbase/var/lib/couchbase/logs/"
    state: absent

- name: SYNC GATEWAY | Create sync_gateway logs directory on Windows
  become: no
  win_file:
    path: "C:/PROGRA~2/Couchbase/var/lib/couchbase/logs/"
    state: directory

- name: SYNC GATEWAY | Delete sync_gateway logs on Windows
  become: no
  win_file:
    path: "C:/Users/Administrator/AppData/Local/Temp/sg_logs/"
    state: absent

- name: SYNC GATEWAY | Delete sync_gateway logs directory under Temp on Windows
  become: no
  win_file:
    path: "C:/Users/Administrator/AppData/Local/Temp/sg_logs/"
    state: directory

- name: SYNC GATEWAY | Delete sync_gateway logs on Windows
  become: no
  win_file:
    path: "C:/tmp/sg_logs/"
    state: absent

- name: SYNC GATEWAY | Create sync_gateway logs directory under c:/tmp on Windows
  become: no
  win_file:
    path: "C:/tmp/sg_logs/"
    state: directory