- name: SG ACCEL | Copy sg_accel config to Windows host
  win_template:
    src: "{{ sync_gateway_config_filepath }}"
    dest: 'C:\PROGRA~2\Couchbase\basic_sg_accel_config.json'

- name: SG ACCEL | Check deployed config
  win_shell: type C:\PROGRA~2\Couchbase\basic_sg_accel_config.json
  register: out

- name: SG ACCEL | Print deployed config
  debug: var=out.stdout