- name: SYNC GATEWAY | Copy sync gateway config to host
  become: yes
  template: src={{ sync_gateway_config_filepath }} dest=/Users/sync_gateway/sync_gateway.json owner=sync_gateway group=sync_gateway mode=0644 force=true

# Deleting cert directory if exist
- name: Deleting /Users/sync_gateway/certs directory
  file:
    state: absent
    path: /Users/sync_gateway/certs/
  become: yes
  when: x509_auth

- name: Deleting /Users/sync_gateway/certs.zip
  file:
    state: absent
    path: /Users/sync_gateway/certs.zip
  become: yes
  when: x509_auth

# Copy certs to /Users/sync_gateway dir
- name: Copying certs.zip to /Users/sync_gateway directory
  copy:
    owner: sync_gateway
    src: /tmp/certs.zip
    dest: /Users/sync_gateway/
    remote_src: yes
    force: yes
  when: x509_auth
  become: yes


# unzip certs.zip
- name: Unzipping certs.zip
  shell: unzip /Users/sync_gateway/certs.zip -d /Users/sync_gateway/certs
  when: x509_auth
  become: yes

- name: SYNC GATEWAY | Check deployed config
  become: yes
  shell: cat /Users/sync_gateway/sync_gateway.json
  register: out

- name: SYNC GATEWAY | Print deployed config
  debug: var=out.stdout

- name: SYNC GATEWAY | Deploying SSL Cert
  become: yes
  template: src="{{ sg_cert_path }}/sg_cert.pem" dest=/Users/sync_gateway/sg_cert.pem owner=sync_gateway group=sync_gateway mode=0644 force=true
  when: sslcert is defined

- name: SYNC GATEWAY | Deploying SSL Private Key
  become: yes
  template: src="{{ sg_cert_path }}/sg_privkey.pem" dest=/Users/sync_gateway/sg_privkey.pem owner=sync_gateway group=sync_gateway mode=0644 force=true
  when: sslkey is defined
