- name: SYNC GATEWAY | Fetch sync_gateway code coverage files
      ansible.builtin.fetch:
        src: /tmp/coverage/
        dest: /tmp/
        flat: yes
      register: fetch_result

- name: Display fetch result
      debug:
        var: fetch_result
