- name: Find files starting with "cov"
  find:
    paths: /tmp/coverage
    patterns: 'cov*'
    recurse: no
  register: found_files

- debug: "{{found_files}}"

- name: Fetch the files
  fetch:
    src: /tmp/coverage/"{{item}}"
    dest: /tmp/coverage
    flat: yes
  loop: "{{ found_files.files }}"