# Fetch sync gateway logs for CentOS
- name: SYNC GATEWAY | Check if sync_gateway error log is present
  become: yes
  stat:
    path: '/home/sync_gateway/logs/sync_gateway_error.log'
  register: sge

- name: SYNC GATEWAY | Fetch sync_gateway error log
  become: yes
  # Do not validate checksum as this is just a passive grab of the logs. Since they are continuously being appended to, the checksum may fail
  fetch: src=/home/sync_gateway/logs/sync_gateway_error.log dest=/tmp/sg_logs/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes validate_checksum=no
  when: sge.stat.exists

- name: SYNC GATEWAY | Check if sg error log is present
  become: yes
  stat:
    path: '/home/sync_gateway/logs/sg_error.log'
  register: se

- name: SYNC GATEWAY | Fetch sg error log
  become: yes
  # Do not validate checksum as this is just a passive grab of the logs. Since they are continuously being appended to, the checksum may fail
  fetch: src=/home/sync_gateway/logs/sg_error.log dest=/tmp/sg_logs/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes validate_checksum=no
  when: se.stat.exists

- name: SYNC GATEWAY | Check if sg info log is present
  become: yes
  stat:
    path: '/home/sync_gateway/logs/sg_info.log'
  register: sgi

- name: SYNC GATEWAY | Fetch sg info logs
  become: yes
  # Do not validate checksum as this is just a passive grab of the logs. Since they are continuously being appended to, the checksum may fail
  fetch: src=/home/sync_gateway/logs/sg_info.log dest=/tmp/sg_logs/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes validate_checksum=no
  when: sgi.stat.exists

- name: SYNC GATEWAY | Check if sg warn log is present
  become: yes
  stat:
    path: '/home/sync_gateway/logs/sg_warn.log'
  register: sgw

- name: SYNC GATEWAY | Fetch sg warn logs
  become: yes
  # Do not validate checksum as this is just a passive grab of the logs. Since they are continuously being appended to, the checksum may fail
  fetch: src=/home/sync_gateway/logs/sg_warn.log dest=/tmp/sg_logs/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes validate_checksum=no
  when: sgw.stat.exists

- name: SYNC GATEWAY | Check if sync gateway access log  is present
  become: yes
  stat:
    path: '/home/sync_gateway/logs/sync_gateway_access.log'
  register: sgal

- name: SYNC GATEWAY | Fetch sync gateway access log  logs
  become: yes
  # Do not validate checksum as this is just a passive grab of the logs. Since they are continuously being appended to, the checksum may fail
  fetch: src=/home/sync_gateway/logs/sync_gateway_access.log dest=/tmp/sg_logs/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes validate_checksum=no
  when: sgal.stat.exists