- name: Getting directory of files
  win_shell: Get-ChildItem | where {!$_.PsIsContainer} | foreach { $_.Name }
  args:
    chdir: "{{ custom_cbl_log_dir }}"
  register: files_to_copy

- name: Fetch logs
  fetch: src={{ custom_cbl_log_dir }}/{{ item }} dest={{ log_full_path }} fail_on_missing=yes flat=yes validate_checksum=no
  with_items: "{{ files_to_copy.stdout_lines }}"