
- name: Find files starting with "cov"
  find:
    paths: /tmp/coverage
    patterns: "cov*"
    recurse: no
  register: found_files

- name: Fetch the files
  fetch: src="{{ item.path }}" dest=/tmp/coverage flat=yes loop="{{ found_files.files }}"
