- name: Find files starting with "cov"
  find:
    paths: /tmp/coverage
    patterns: 'cov*'
    recurse: no
  register: found_files

- name: Print all the found files
  debug:
    msg: "{{item}}"
  with_items: "{{found_files}}"

- name: Fetch the files
  fetch: src="{{item['path']}}" dest=/tmp/coverage/ flat=yes
  with_items: "{{found_files}}"