# Stop nginx service
- name: NGINX | stop nginx service
  become: yes
  service: name=nginx state=stopped
  ignore_errors: yes

- name: NGINX | Remove nginx package
  become: yes
  yum: pkg=nginx state=absent
  ignore_errors: yes
