# Remove sync_gateway package
- name: SG ACCEL | Uninstall sync_gateway_accel exe
  win_command: wmic product where name='Couchbase Sync Gateway Accelerator' call uninstall

# Delete sync_gateway binary
- name: SG ACCEL | Delete sync_gateway_accel install directory
  win_file: 
    path: C:\PROGRA~2\Couchbase 
    state: absent
  ignore_errors: yes

- name: SG ACCEL | Remove tmp logging dir (log rotation tests)
  win_file: 
    path: C:\Users\Administrator\AppData\Local\Temp\sg_logs
    state: absent
  ignore_errors: yes