  - name: SYNC GATEWAY | Check if sync_gateway redacted zip file exists under {{ sg_logs_dir }}
    become: yes
    shell: ls *.zip
    register: files_to_copy
    args:
      chdir: "{{ sg_logs_dir }}"

  - name: SYNC COLLECT FETCH | sg collect fetching redacted zip file from {{ sg_logs_dir }}
    become: yes
    fetch: src={{ sg_logs_dir }}/{{ files_to_copy.stdout_lines[0] | replace('[', '') | replace(']', '') | replace("'", '') }} dest=/tmp/sg_redaction_logs/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes validate_checksum=no

 # A workaround because of a problem with a loop - it doesn't treat files_to_copy.stdout_lines as a list
 # but rather as a string. We therefore access the items directly.
  - name: SYNC COLLECT FETCH | sg collect fetching the second zip file{{ sg_logs_dir }}
    become: yes
    fetch: src={{ sg_logs_dir }}/{{ files_to_copy.stdout_lines[1] | replace('[', '') | replace(']', '') | replace("'", '') }} dest=/tmp/sg_redaction_logs/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes validate_checksum=no
    when:  "{{ files_to_copy.stdout_lines | length == 2 }}"