
  # Copy machine stat collection script to sync_gateways
  - name: SYNC COLLECT START | sg collect started on Windows
    win_shell: C:\PROGRA~1\Couchbase\SYNCGA~1\tools\sgcollect_info.exe --log-redaction-level={{ redact_level }} {{ salt_value }} {{ zip_file_name }}
    args:
      chdir: C:\PROGRA~2\Couchbase\var\

  - name: SYNC GATEWAY | Check if sync_gateway redacted zip file exists
    win_stat:
      path: 'C:\PROGRA~2\Couchbase\var\{{ zip_file_name }}-redacted.zip'
    register: sgz

  - name: SYNC COLLECT FETCH | sg collect fetching redacted zip file to {{ inventory_hostname }}
    vars:
      var: var
    fetch: src=C:\PROGRA~2\Couchbase\{{ var }}\{{ zip_file_name }}-redacted.zip dest=/tmp/sg_redaction_logs/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes validate_checksum=no
    when: sgz.stat.exists

  - name: SYNC COLLECT FETCH | sg collect fetching non redacted zip file to {{ inventory_hostname }}
    vars:
      var: var
    fetch: src=C:\PROGRA~2\Couchbase\{{ var }}\{{ zip_file_name }}.zip dest=/tmp/sg_redaction_logs/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes validate_checksum=no
