- debug: msg="Starting sync_gateway with config {{ sync_gateway_config_filepath }}"

- name: SYNC GATEWAY | Start sync_gateway service on Windows
  win_service:
    name: SyncGateway
    state: started