- debug: msg="Starting sg_accel with config {{ sync_gateway_config_filepath }}"
- name: start sg_accel service
  service: name=sg_accel state=started
- name: wait until sg_accel to listen on port
  wait_for: port=4985 delay=2 timeout=120

