---
- hosts: sync_gateways
  remote_user: centos
  any_errors_fatal: true
  become: yes
  tasks:

  # Fetch generated profile results
  tasks:
  - name: Fetch sync gateway profile
    fetch: src=/tmp/sync_gateway_profile.tar.gz dest=/tmp/sync_gateway_profile/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes
    when: "'sync_gateway_index_writers' not in group_names"
  - name: Tell user where to find the profile data
    debug: msg="Profile data has been saved in /tmp/sync_gateway_profile.tar.gz"
    when: "'sync_gateway_index_writers' not in group_names"

- hosts: sync_gateway_index_writers
  remote_user: centos
  any_errors_fatal: true
  become: yes
  tasks:

  # Fetch generated profile results on sg_accels
  tasks:
  - name: Fetch sync gateway profile
    fetch: src=/tmp/sync_gateway_profile.tar.gz dest=/tmp/sync_gateway_profile/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes
  - name: Tell user where to find the profile data
    debug: msg="Profile data has been saved in /tmp/sync_gateway_profile.tar.gz"

