=== Setup Controller on OSX

The "controller" is the machine that runs the tests and communicates with the system under test, which is typically:

* Your developer workstation
* A virtual machine / docker container

The instructions below are for setting up directly on OSX.  If you prefer to run this under Docker, see the https://github.com/couchbaselabs/mobile-testkit/wiki/Running-under-Docker[Running
under Docker] wiki page.

=== Install Python via brew

If you are on OSX El Capitan, you must install python via brew rather than using the system python due to https://github.com/pypa/pip/issues/3165[Pip issue 3165].

```
$ brew install python
```

After you install it, you should see that the python installed via brew is the default python:

```
$ which python
/usr/local/bin/python
$ python --version
Python 2.7.10
```

=== Install libcouchbase

On MacOSX
```
$ brew install libcouchbase
```

On CentOS7
```
$ yum install gcc libffi-devel python-devel openssl-devel
```

```
$ yum install -y libev libevent
$ wget http://packages.couchbase.com/clients/c/libcouchbase-2.5.6_centos7_x86_64.tar && \
    tar xvf libcouchbase-2.5.6_centos7_x86_64.tar && \
    cd libcouchbase-2.5.6_centos7_x86_64 && \
    rpm -ivh libcouchbase-devel-2.5.6-1.el7.centos.x86_64.rpm \
             libcouchbase2-core-2.5.6-1.el7.centos.x86_64.rpm \
	     libcouchbase2-bin-2.5.6-1.el7.centos.x86_64.rpm \
	     libcouchbase2-libevent-2.5.6-1.el7.centos.x86_64.rpm && \
    rm -f *.rpm	     
```

If you run into this error when running `source setup.sh`:

```
  src/pycbc.h:29:31: fatal error: libcouchbase/cbft.h: No such file or directory
     #include <libcouchbase/cbft.h>
```

The update your libcouchbase version via:

```
wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-x86_64.rpm
sudo rpm -iv couchbase-release-1.0-2-x86_64.rpm
sudo yum install libcouchbase-devel libcouchbase2-bin gcc gcc-c++
```


=== Set up virtualenv install python dependencies

```
$ [sudo] pip install virtualenv
```

```
$ cd mobile-testkit/
```

Setup PATH, PYTHONPATH, and ANSIBLE_CONFIG
```
source setup.sh
```

If you plan on doing development, it may be helpful to add the PYTHONPATH env variables to your .bashrc file so that you do not have to run this setup everytime you open a new shell.
