# Stop sync_gateway service
- name: stop sync_gateway service
  service: name=sync_gateway state=stopped
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  ignore_errors: yes

- name: stop sync_gateway for CentOS 6
  shell: /sbin/initctl stop sync_gateway
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  ignore_errors: yes

- name: verify sync_gateway not listening on port
  wait_for: port=4985 delay=1 state=stopped

# Remove package
- name: Uninstall sync_gateway rpm
  shell: rpm -e couchbase-sync-gateway
  ignore_errors: yes

# Remove service
- name: Remove sync_gateway service
  shell: rm /usr/lib/systemd/system/sync_gateway.service
  ignore_errors: yes

# Delete sync_gateway binary
- name: delete sync_gateway binary
  shell: rm -rf /opt/couchbase-sync-gateway

# Delete logs and .pindex files
- name: delete sync_gateway logs
  shell: rm -f /home/sync_gateway/logs/*.log
- name: delete sync_gateway pindex files
  shell: rm -rf /home/sync_gateway/*.pindex

# Remove sync_gateway user
- name: remove sync gateway user
  user: name=sync_gateway state=absent remove=yes force=yes
  ignore_errors: yes

# Delete downloaded source
- name: delete previous sync gateway
  command: rm -rf /home/centos/sync_gateway