# Stop service
- name: stop sync_gateway service
  service: name=sync_gateway state=stopped
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
- name: stop sync_gateway for CentOS 6
  shell: /sbin/initctl stop sync_gateway
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
- name: verify sync_gateway not listening on port
  wait_for: port=4985 delay=1 state=stopped

# Delete logs and .pindex files
- name: delete sync_gateway logs
  shell: rm -f /home/sync_gateway/logs/*.log
- name: delete sync_gateway pindex files
  shell: rm -rf /home/sync_gateway/*.pindex

