# Stop sync_gateway service
- name: stop sg_accel service
  service: name=sg_accel state=stopped
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  ignore_errors: yes

- name: stop sg_accel for CentOS 6
  shell: /sbin/initctl stop sg_accel
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  ignore_errors: yes

- name: verify sg_accel not listening on port
  wait_for: port=4985 delay=1 state=stopped

# Remove sg_accel package
- name: Uninstall sg_accel rpm
  shell: rpm -e couchbase-sg-accel
  ignore_errors: yes

# Remove sg_accel service
- name: Remove sg_accel service
  file: path=/usr/lib/systemd/system/sg_accel.service state=absent
  ignore_errors: yes

# Delete sg_accel binary
- name: delete sync_gateway binary
  file: path=/opt/couchbase-sg-accel state=absent
